targets = [ "//:webp" ]

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libjpeg"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libpng"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libtiff"
version = "branch=master"
